name: Run Gift Automation

on:
  workflow_dispatch:
  push:
    paths:
      - 'grouped_result.json'

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install beautifulsoup4 requests

    - name: Flatten grouped_result.json → products.json
      run: python scripts/flatten_grouped_json.py

    - name: Add Coupang links → products_with_links.json
      run: python scripts/add_coupang_links.py

    - name: Commit and push result
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git add products.json products_with_links.json
        git commit -m 'Auto update products_with_links.json [CI]' || echo "No changes"
        git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
